### ISSUE TITLE
LAB#8 Haffman

### ISSUE THREAD

**Issue by kazyritskii** [kazyritskii/Projects#3]
https://github.com/kazyritskii/Projects/tree/master/Laboratory8

**Comment by kazyritskii** [comment]
Доделал Хаффмана, тесты все проходит

**Comment by avkomar** [comment]
1. Сделайте улучшение структуры кода, разбиение на заголовочные и файлы реализации для раздельной компиляции.
2. Избавьтесь от создания промежуточного текстового файла `buffer.txt`
