### ISSUE TITLE
LAB#10 Topolog Sort

### ISSUE THREAD

**Issue by kazyritskii** [kazyritskii/Projects#4]
https://github.com/kazyritskii/Projects/tree/master/Laboratory10

**Comment by avkomar** [comment]
Обновите код на рабочую версию, которая проходит все тесты, пожалуйста.

**Comment by kazyritskii** [comment]
Обновил код, переделал списки смежности.

**Comment by avkomar** [comment]
1. для кодов возврата и цветов вершин лучше использовать именованные константы, а не просто числа.
2. написана функция `freeHead2`, которая походу в конце пытается очистить нулевой указатель. Но эта функция ни разу не вызывается и память, выделенная  с помощью `malloc`, не освобождается.

В остальном замечаний по коду нет. В терминальном классе еще задам пару вопросов.
